[package]
name = "nvidia_riva"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.20", features = ["time", "test-util", "fs", "macros", "sync", "rt-multi-thread"] }
tonic = "0.8"

[build-dependencies]
anyhow = "1.0"
tonic-build = "0.8"
